version: "3.3"
services:
  leader:
    image: toy-distributed-key-value
    command: run --leader
    networks:
      - kv
  follower:
    image: toy-distributed-key-value
    command: run
    networks:
      - kv
    depends_on:
      - leader

  tester:
    image: toy-distributed-key-value
    command: test
    networks:
      - kv
    depends_on:
      - leader
      - follower

networks:
  kv:
    driver: bridge
